aluno1 = Aluno('Victor','victor@rj.senac.br', '12345', 'Programação')
aluno2 = Aluno('Thamires','thamires@rj.senac.br', '12345', 'Banco de Dados I')
prof1 = Professor('Roberto', 'roberto.harkovsky@rj.senac.br', '12345', 'MsC')
print(aluno1.consulta_dados())
print(aluno1.consulta_curso())
print(aluno2.consulta_dados())
print(aluno2.consulta_curso())
print(prof1.consulta_nome())
print(prof1.consulta_titulacao())